baseURL = "https://pudymody.netlify.com/"
languageCode = "en-us"
title = "Federico Scodelaro"
googleAnalytics = "UA-75819066-1"
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pygmentsCodefences=true
pygmentsStyle="vs"
pluralizeListTitles  = false
[taxonomies]
[[menu.main]]
    name = "baby steps"
    url = "/taringa"
[[menu.main]]
    name = "blog"
    url = "/blog"
[[menu.main]]
    name = "readlist"
    url = "/books"
[[menu.main]]
    name = "bookmarks"
    url = "/bookmarks"
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Hi, this is my personal blog where i write about my project, nonsense and useless ideas. At the moment i'm trying to improve and develop my skills. I'm available for freelance project so don't be scared of getting in touch with me."
